WebsiteBanSach/WebsiteBanSach/Controllers/UserHomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;
using WebsiteBanSach.Models;

namespace WebsiteBanSach.Controllers
{
    public class UserHomeController : Controller
    {
        BookShopEntities db = new BookShopEntities();
        // GET: UserHome
        public ActionResult Index()
        {
            
            //lấy sách bán chạy
            string sql= "select * " +
                        "from Book " +
                        "where Book.BookID in (select BookID " +
                                              "from(Select top(5) c.BookID, SUM(c.Quantity) as sumQuantity " +
                                                      "from Cart as c  , dbo.DonDatHang as ddh " +
                                                      "where c.DDH_ID = ddh.DDH_ID and ddh.OrderDate <= GETDATE() and ddh.OrderDate >= (GETDATE() - 7) and ddh.isDelivered = 'true' " +
                                                      "group by BookID " +
                                                      "order by(sumQuantity) DESC " +
                                                      ")a  " +
                                               ") ";



            List<Book> BookIDList = db.Database.SqlQuery<Book>(sql).ToList();
            
            return View(BookIDList);

        }

        public ActionResult Test()
        {
            return View();
        }
        //menu: danh mục >> tác giả>>sách của tác giả
        public ActionResult LoadDanhMucSach(int? CageID)
        {
            var SachList = db.Books;
            

            return PartialView(SachList);
        }

        

        public ActionResult LoadSachTheoDanhMuc(int? CageID, int? Page)//dâu hỏi vì int 32 hoặc int 64; page: trang hiên tại
        {
            
            if (CageID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);//lỗi 400-k tìm thấy
            }
            var ListSach = db.Books.Where(s => s.CategoryId == CageID && s.isDelete == false);
            if (ListSach == null)
            {
                return HttpNotFound();
            }

            

            //phân trang bằng thư viện pagedlist
            int pageSize = 4;
            int pageNumber = (Page ?? 1);//phép gán: nếu Page k chưa giá trị thì mặc định bằng 1
            ViewBag.CageID = CageID;
            return View(ListSach.OrderBy(s=>s.CategoryId).ToPagedList(pageNumber,pageSize));
        }
        public ActionResult LoadSachTheoDanhMucVaTacGia(int? CageID, int? AuthorID)//dâu hỏi vì int 32 hoặc int 64
        {

            if (CageID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);//lỗi 400-k tìm thấy
            }
            var ListSach = db.Books.Where(s => s.CategoryId == CageID && s.AuthorID==AuthorID && s.isDelete == false);
            if (ListSach == null)
            {
                return HttpNotFound();
            }
            Author ThongTinTacGia = db.Authors.SingleOrDefault(tg => tg.AuthorID == AuthorID);
            ViewBag.ThongTinTacGia = ThongTinTacGia;

            
            return View(ListSach);
        }


        public ActionResult XemChiTietSach(int? BookID, int? AuthorID, string AuthorName)
        {
            if (BookID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);//lỗi 400-k tìm thấy
            }
            var Sach = db.Books.SingleOrDefault(s => s.BookID == BookID && s.isDelete == false);
            if (Sach == null)
            {
                return HttpNotFound();
            }
            if (AuthorName != null)
            {
                ViewBag.AuthorName = AuthorName;
            }
            else
            {
                Author TacGia = db.Authors.SingleOrDefault(tg => tg.AuthorID == Sach.AuthorID);
                ViewBag.AuthorName = TacGia.AuthorName;
            }
            
            ////mang tên tác giả qau trang chi tiết
            //var TenTacGia = db.Authors.SingleOrDefault(tg=>tg.AuthorID==AuthorID);
            //ViewBag.TenTacGia = TenTacGia;
            return View(Sach);
        }

     
        public ActionResult DangNhap(FormCollection f)
        {
            string Username = f["txtUsername"].ToString();
            string Password = f["txtPassword"].ToString();
            Customer CurrentUser = db.Customers.SingleOrDefault(u => u.CusUserName == Username && u.CusPass == Password);
            if (CurrentUser != null)
            {
                Session["Current_User"] = CurrentUser;
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public ActionResult DangXuat()
        {
            Session["Current_User"] = null;
            return RedirectToAction("Index");
        }
    }
}

WebsiteBanSach/WebsiteBanSach/Views/UserHome/Index.cshtml
@using WebsiteBanSach.Models
@model IEnumerable<Book>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/UserIndexLayout.cshtml";
}

<div id="home-carousel" class="carousel carousel-home slide" data-ride="carousel" data-interval="5000">
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        @for (int i = 0; i < 5; i++)
        {
            if (i == 0)
            {
                <div class="active item">
                    <section class="site-section site-section-light site-section-top themed-background-dark-default">
                        <div class="container">
                            <h1 class="text-center animation-slideDown hidden-xs"><strong>Sách HOT Trong Tuần</strong></h1>
                            <h2 class="text-center animation-slideUp push hidden-xs">Đừng bỏ lỡ cơ hội sở hữu những cuốn sách đang làm mưa làm gió hiện nay!</h2>
                            <p class="text-center animation-fadeIn">
                                <img src="@Url.Content("~/Content/HinhAnhSach/"+Model.ElementAt(i).Image)" alt="Promo Image 1" style="width:400px; height:450px;">
                            </p>
                        </div>
                    </section>
                </div>
            }
            else
            {
                <div class="item">
                    <section class="site-section site-section-light site-section-top themed-background-dark-default">
                        <div class="container">
                            <h1 class="text-center animation-slideDown hidden-xs"><strong>Sách HOT Trong Tuần</strong></h1>
                            <h2 class="text-center animation-slideUp push hidden-xs">Đừng bỏ lỡ cơ hội sở hữu những cuốn sách đang làm mưa làm gió hiện nay!</h2>
                            <p class="text-center animation-fadeIn">
                                <img src="@Url.Content("~/Content/HinhAnhSach/"+Model.ElementAt(i).Image)" alt="Promo Image 1" style="width:400px; height:450px;">
                            </p>
                        </div>
                    </section>
                </div>
            }

        }

    </div>
    <!-- END Wrapper for slides -->
    <!-- Controls -->
    <a class="left carousel-control" href="#home-carousel" data-slide="prev">
        <span>
            <i class="fa fa-chevron-left"></i>
        </span>
    </a>
    <a class="right carousel-control" href="#home-carousel" data-slide="next">
        <span>
            <i class="fa fa-chevron-right"></i>
        </span>
    </a>
    <!-- END Controls -->
</div>
<!-- END Home Carousel -->
<!-- Action -->
<section class="site-content site-section">
    <div class="container">
        <div class="site-block text-center">
            <a href="#" class="btn btn-lg btn-success"><i class="fa fa-shopping-cart"></i> Sách Bán Chạy Trong Tuần</a>

        </div>
        <hr>
    </div>
</section>

<!-- Promo #1 -->
@for (int i = 0; i < 5; i++)
{
    if (i % 2 == 0)
    {
        <section class="site-content site-section site-slide-content">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInRight" data-element-offset="-180">
                        <img src="@Url.Content("~/Content/HinhAnhSach/"+Model.ElementAt(i).Image)" alt="Promo #1" class="img-responsive" style="width:400px; height:450px;">
                    </div>
                    <div class="col-sm-6 col-md-5 col-md-offset-1 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInLeft" data-element-offset="-180">
                        <h3 class="h2 site-heading site-heading-promo"><strong>@Model.ElementAt(i).BookName</strong></h3>
                        <p class="promo-content">@Model.ElementAt(i).Description.Substring(0, 300) [...] <a href="features.html">Xem chi tiết...</a></p>
                    </div>
                </div>
                <hr>
            </div>
        </section>
        <!-- END Promo #1 -->
    }
    else
    {
        <!-- Promo #2 -->
        <section class="site-content site-section site-slide-content">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-5 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInRight" data-element-offset="-180">
                        <h3 class="h2 site-heading site-heading-promo"><strong>@Model.ElementAt(i).BookName</strong></h3>
                        <p class="promo-content">@Model.ElementAt(i).Description.Substring(0, 300) [...] <a href="features.html">Xem chi tiết...</a></p>
                    </div>
                    <div class="col-sm-6 col-md-offset-1 site-block visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInLeft" data-element-offset="-180">
                        <img src="@Url.Content("~/Content/HinhAnhSach/"+Model.ElementAt(i).Image)" alt="Promo #2" class="img-responsive" style="width:400px; height:450px;">
                    </div>
                </div>
                <hr>
            </div>
        </section>
        <!-- END Promo #2 -->
    }
}

WebsiteBanSach/WebsiteBanSach/Views/UserHome/LoadDanhMucSach.cshtml
@using WebsiteBanSach.Models
@model IEnumerable<Book>



<div class="sidebar-block">
        <ul class="store-menu">
            @foreach (var CategoryGroup in Model.GroupBy(category=>category.Category))
            {
                <li id="DanhMucSach">
                    
                    <a href="@Url.Action("LoadSachTheoDanhMuc","UserHome",new {CageID=CategoryGroup.Key.CategoryID})" class="submenu"><i class="fa fa-angle-right"></i> @CategoryGroup.Key.CategoryName</a>
                    <ul id="TacGia">
                        @foreach (var AuthorGroup in CategoryGroup.GroupBy(author => author.Author))
                        {
                            <li><a href="@Url.Action("LoadSachTheoDanhMucVaTacGia","UserHome",new {CageID=CategoryGroup.Key.CategoryID, AuthorID=AuthorGroup.Key.AuthorID })">@AuthorGroup.Key.AuthorName</a></li>
                        }


                    </ul>
                </li>
            }


        </ul>
</div>
<style>
    #DanhMucSach:hover #TacGia{
        display:block;
    }
</style>

WebsiteBanSach/WebsiteBanSach/Views/UserHome/LoadSachTheoDanhMuc.cshtml
@using WebsiteBanSach.Models
@using PagedList.Mvc;
@*Class giúp hiển thị sản phẩm tương ứng với số trang*@
@model PagedList.IPagedList<Book>
@{
    ViewBag.Title = "LoadSachTheoDanhMuc";
    Layout = "~/Views/Layout/MainUserLayout.cshtml";
}
<!-- ajax -->
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<div class="row store-items">

    @foreach (var item in Model)
    {
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="@Url.Action("XemChiTietSach","UserHome",new {BookID=item.BookID})">
                        <img src="@Url.Content("~/Content/HinhAnhSach/"+item.Image)" alt="not found" class="img-responsive" style="width:400px; height:300px;">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">@item.Price.Value.ToString("#,##") VNĐ</span>
                    <a href="@Url.Action("XemChiTietSach","UserHome",new {BookID=item.BookID})">
                        <strong>@item.BookName</strong>
                    </a><br>
                    @*Nút thêm vào giỏ hàng; request.url: lấy đường dẫn hiện tại*@
                        <small><i class="fa fa-shopping-cart text-muted"></i>  @Ajax.ActionLink("Thêm vào giỏ hàng", "ThemGioHangAjax", "GioHang", new { @_BookID = item.BookID, @urlPath = Request.Url.ToString() }, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "divGioHang", InsertionMode = InsertionMode.Replace }, new {@class="text-muted" })</small>

                </div>
                
            </div>
        </div>
    }


    @*<div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo28.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 59</span>
                    <a href="ecom_product.html"><strong>Gloves</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo30.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 99</span>
                    <a href="ecom_product.html"><strong>Jacket</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo32.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 79</span>
                    <a href="ecom_product.html"><strong>Headset</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo35.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 1.599</span>
                    <a href="ecom_product.html"><strong>Laptop</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo33.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 149</span>
                    <a href="ecom_product.html"><strong>Sunglasses</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>*@
</div>

<div class="dlink" style="margin-right:0;">

    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    @*PagedListPager:Tách sản phẩm thành nhiều trang
       Model: list sách mỗi trang(4)
       page: trỏ tới link ở trang kế tiếp 
    *@
    @Html.PagedListPager(Model, pageID => Url.Action("LoadSachTheoDanhMuc", new { Page = pageID, @CageID=ViewBag.CageID}))
</div>

WebsiteBanSach/WebsiteBanSach/Views/UserHome/LoadSachTheoDanhMucVaTacGia.cshtml
@using WebsiteBanSach.Models


@{
    ViewBag.Title = "LoadSachTheoDanhMucVaTacGia";
    Layout = "~/Views/Layout/MainUserLayout.cshtml";
}
<!-- ajax -->
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<div class="row store-items">
    @{ 
        Author TacGia = (Author)ViewBag.ThongTinTacGia;
    }
    <h2 style="color:darkslateblue; font-weight:500">Tác Giả: @TacGia.AuthorName</h2>
    <div style="font-family:'Bookman Old Style'">
        @TacGia.Description
    </div>
    <hr />
    @foreach (var item in Model)
    {
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="@Url.Action("XemChiTietSach","UserHome",new {BookID=item.BookID, AuthorName=TacGia.AuthorName})">
                        <img src="@Url.Content("~/Content/HinhAnhSach/"+item.Image)" alt="not found" class="img-responsive" style="width:400px; height:300px;">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">@item.Price.ToString("#,##") VNĐ</span>
                    <a href="@Url.Action("XemChiTietSach","UserHome",new {BookID=item.BookID, AuthorName=TacGia.AuthorName})">
                        <strong>@item.BookName</strong>
                    </a><br>
                    @*Nút thêm vào giỏ hàng; request.url: lấy đường dẫn hiện tại*@
                    <small><i class="fa fa-shopping-cart text-muted"></i>  @Ajax.ActionLink("Thêm vào giỏ hàng", "ThemGioHangAjax", "GioHang", new { @_BookID = item.BookID, @urlPath = Request.Url.ToString() }, new AjaxOptions { HttpMethod = "get", UpdateTargetId = "divGioHang", InsertionMode = InsertionMode.Replace }, new { @class = "text-muted" })</small>

                </div>

            </div>
        </div>
    }


    @*<div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo28.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 59</span>
                    <a href="ecom_product.html"><strong>Gloves</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo30.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 99</span>
                    <a href="ecom_product.html"><strong>Jacket</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo32.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 79</span>
                    <a href="ecom_product.html"><strong>Headset</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo35.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 1.599</span>
                    <a href="ecom_product.html"><strong>Laptop</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>
        <div class="col-md-6 visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick" data-element-offset="-100">
            <div class="store-item">
                <div class="store-item-rating text-warning">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                </div>
                <div class="store-item-image">
                    <a href="ecom_product.html">
                        <img src="img/placeholders/photos/photo33.jpg" alt="" class="img-responsive">
                    </a>
                </div>
                <div class="store-item-info clearfix">
                    <span class="store-item-price themed-color-dark pull-right">$ 149</span>
                    <a href="ecom_product.html"><strong>Sunglasses</strong></a><br>
                    <small><i class="fa fa-shopping-cart text-muted"></i> <a href="javascript:void(0)" class="text-muted">Add to cart</a></small>
                </div>
            </div>
        </div>*@
</div>

WebsiteBanSach/WebsiteBanSach/Views/UserHome/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Layout/MainUserLayout.cshtml";
}

<h2>Test</h2>